baseURL = "https://lucky0-gif.github.io/"
languageCode = "zh-cn"
title = "DoJo"
theme = "PaperMod"

[params]
googleAnalytics = ""
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = false
ShowContentOnHomepage = true


[params.homeInfoParams]
Title = "有些东西无法分类，只能慢慢编织。"
Content = "这里记录一些尝试，把混乱编织成系统，把碎片变成路径。不是答案，只是探索的痕迹。"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[menu.main]]
identifier = "featured-diary"
name = "精选日记"
url = "/featured-diary/"
weight = 10

[[menu.main]]
identifier = "latest-records"
name = "最新记录"
url = "/latest-records/"
weight = 20

[[menu.main]]
identifier = "my-footprints"
name = "我的足迹"
url = "/my-footprints/"
weight = 30

[[menu.main]]
identifier = "plans-and-reflections"
name = "计划与回顾"
url = "/plans-and-reflections/"
weight = 40

[[menu.main]]
identifier = "site-purpose"
name = "创站初衷"
url = "/site-purpose/"
weight = 50

[[menu.main]]
identifier = "message-board"
name = "留言板"
url = "/message-board/"
weight = 60