baseURL = "https://lucky0-gif.github.io/"
languageCode = "zh-cn"
title = "DoJo"
theme = "PaperMod"

[params]
googleAnalytics = ""
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = false
ShowContentOnHomepage = true


[params.homeInfoParams]
Title = "有些东西无法分类，只能慢慢编织。"
Content = "这里记录一些尝试，把混乱编织成系统，把碎片变成路径。不是答案，只是探索的痕迹。"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[menu.main]]
identifier = "前端开发"
name = "前端开发"
url = "/frontend/"
weight = 10

[[menu.main]]
identifier = "后端开发"
name = "后端开发"
url = "/backend/"
weight = 20

[[menu.main]]
identifier = "移动开发"
name = "移动开发"
url = "/mobile-dev/"
weight = 30

[[menu.main]]
identifier = "数据科学"
name = "数据科学"
url = "/data-science/"
weight = 40

[[menu.main]]
identifier = "开发工具"
name = "开发工具"
url = "/dev-tools/"
weight = 50

[[menu.main]]
identifier = "归档"
name = "归档"
url = "/archives/"
weight = 60
